sudo: required
language: generic
matrix:
  include:
  - os: linux
    python: 2.7
    env: TRAVIS_PYTHON_VERSION=2.7
  - os: osx
    python: 2.7
    env: TRAVIS_PYTHON_VERSION=2.7
before_install:
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda install -y conda-build
  else
    # Install Miniconda
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda install -y conda-build
  fi
script:
- chmod u+x ci/build_and_test.sh
- |
  while sleep 500; do
     echo "====[ $SECONDS seconds still running ]===="
  done &
- ./ci/build_and_test.sh
