package:
   name: xspec-modelsonly
   version: "6.22.1"

source:
#  md5: 0abea9e1609fcdc2c3e3ada92043d17b
  url: https://heasarc.gsfc.nasa.gov/FTP/software/lheasoft/lheasoft6.22.1/xspec-modelsonly-v6.22.1.tar.gz
  fn: xspec-modelsonly-v6.22.1.tar.gz

build:
  number: 0

requirements:
    build:
        - ccfits 2.5 0
        - cfitsio 3.410 2
        - gfortran_osx-64 4.8.5 h22b1bf0_3
        - libgfortran 3.0.1 h93005f0_2
        - libpng 1.6.34 0
        - libxcb 1.12 1
        - ncurses 5.9 10
        - perl 5.20.3.1 2
        - pgplot 5.2.2 2
        - readline 6.2 0
        - toolchain 2.1.2 0
        - wcslib 5.18 2
        - xorg-kbproto 1.0.7 1
        - xorg-libx11 1.6.4 6
        - xorg-libxau 1.0.8 3
        - xorg-libxdmcp 1.1.2 3
        - xorg-xproto 7.0.31 6
        - zlib 1.2.11 0
    run:
        - cfitsio
        - ccfits
        - wcslib
        - readline 6.2
        - libgfortran
        - ncurses

# Note that ncurses is only needed to build but I am not
# sure it's needed at all at run-time. To keep things
# safe and simple I am keeping it, but removing the version
# number since it was only there to make `configure` happy
# and there is no evidence ncurses is required in the
# first place.
#  run:
#    - readline

about:
  home: https://heasarc.gsfc.nasa.gov/xanadu/xspec/
