package:
   name: xspec-modelsonly
   version: "6.20"

source:
  #path: xspec-modelsonly-v6.20-no-big-data.tar.gz
  #url: https://heasarc.gsfc.nasa.gov/FTP/software/lheasoft/release/xspec-modelsonly-v6.21.tar.gz
  url: file:///home/giacomov/develop/conda_3ML/xspec-dist/tars/xspec-modelsonly-v6.20-no-big-data.tar.gz

build:
  number: 0

requirements:
 
 build: 
   - cfitsio
   - ccfits
   - wcslib
   - libgfortran
   - gcc
   - libgcc
 
 run:
   - cfitsio
   - ccfits
   - wcslib
   - libgfortran
   - gcc
   - libgcc

