package:
   name: xspec-modelsonly
   version: "6.20"

source:
  #path: xspec-modelsonly-v6.20-no-big-data.tar.gz
  #url: https://heasarc.gsfc.nasa.gov/FTP/software/lheasoft/release/xspec-modelsonly-v6.21.tar.gz
  url: file:///work/xspec-modelsonly-v6.20-no-big-data.tar.gz

build:
  number: 0

requirements:
 
 build: 
   - cfitsio
   - ccfits
   - wcslib
   - readline
 
 run:
   - cfitsio
   - ccfits
   - wcslib
   - readline

