package:
   name: xspec-modelsonly
   version: "6.22.1"

source:
  #  md5: 0abea9e1609fcdc2c3e3ada92043d17b
  # url: https://heasarc.gsfc.nasa.gov/FTP/software/lheasoft/lheasoft6.22.1/xspec-modelsonly-v6.22.1.tar.gz
  path: ../../xspec-modelsonly-v6.22.1.tar.gz
  #fn: xspec-modelsonly-v6.22.1.tar.gz

build:
  number: 1

requirements:
    build:
      - ccfits==2.5
      - cfitsio==3.410
      - gfortran_osx-64 # [osx]
      - {{ compiler('c') }} # [linux]
      - {{ compiler('cxx') }} # [linux]
      - {{ compiler('fortran') }} # [linux]
      - libgfortran>=3.0,<4.0
      - ncurses==5.9
      - readline==6.2
      - toolchain==2.1.2
      - wcslib==5.18
    run:
      - ccfits==2.5
      - cfitsio==3.410
      - wcslib==5.18
      - libgfortran
      - ncurses==5.9
      - readline==6.2

# Note that ncurses is only needed to build but I am not
# sure it's needed at all at run-time. To keep things
# safe and simple I am keeping it, but removing the version
# number since it was only there to make `configure` happy
# and there is no evidence ncurses is required in the
# first place.
#  run:
#    - readline

about:
  home: https://heasarc.gsfc.nasa.gov/xanadu/xspec/
