package:
   name: cfitsio
   version: "3.410"

source:
  url: http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio3410.tar.gz

build:
  number: 0

requirements:
 
 build: 
   
 run:
   
about:
  home: https://heasarc.gsfc.nasa.gov/fitsio/ccfits/
  license: GPL2
