package:
   name: wcslib
   version: "5.16"

source:
  url: ftp://ftp.atnf.csiro.au/pub/software/wcslib/wcslib-5.16.tar.bz2

build:
  number: 0

requirements:
 
 build: 
   - cfitsio
   
 run:
   - cfitsio
   
about:
  home: https://heasarc.gsfc.nasa.gov/fitsio/ccfits/
  license: GPL2
